export const HETZNER_DNS_API_BASEURL_ENV_NAME = 'HETZNER_DNS_API_BASEURL';
export const HETZNER_DNS_API_TOKEN_ENV_NAME = 'HETZNER_DNS_API_TOKEN';

export const HOMEZONE_SUBDOMAIN_NAME_ENV_NAME = 'HOMEZONE_SUBDOMAIN_NAME';
