name: Build Docker image

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build.yaml' ## This file
    - '**.json'
    - '**.ts'
    - 'Dockerfile'
    - '!.vscode/*'

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      IMAGE_NAME: hetzner-dyndns

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: |
        echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
        echo "::set-output name=sref::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

    - name: Build
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker pull ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}:latest
        docker build . --tag ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}:${{ steps.slug.outputs.sha7}} --cache-from ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}:latest
        docker push ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}
